_LL <- {}

_LL["Fr"] <- {
    counter = "Compteur de jeu",
    playedtime = "Temps en jeu",
    display = "Jeux / Filtre",
    add_fav = "Ajouté au favoris",
    ret_fav = "Retiré des favoris",
    Sday = "J",
    Never = "Jamais",
    RefreshTxt = "Rafraichissement des statistiques",
    Games = "Jeux",
    Played = "Parties",
    Filter_all = "tous",
    Yes = "Oui",
    No = "Non",
    M_Menu_stretch = "Etiré",
    M_Menu_center = "Centrer",
    M_inf_Bezel = "Utiliser les bezels pour les themes HS",
    M_inf_Bezel_top = "Afficher le bezel au dessus des artworks",
    M_inf_str_bckg =  "Etirer les fond d'écran à la résolution actuelle",
    M_inf_flv = "Active/Désactive les transitions FLV",
    M_inf_theme = "Réglage du theme",
    M_inf_bck_trans = "Utiliser les transitions de fond d'écran.",
    M_inf_reload_bck = "Utilise les transitions sur les themes systeme",
    M_inf_aspect = "Aspect du theme (Etire ou centre les thems HS)",
    M_inf_syno = "Montre/cache le synopsis qui défile",
    M_inf_game_sound = "Utiliser les sons ambiance",
    M_inf_wheel_click = "Utiliser les sons de clique pour la wheel",
    M_inf_wheel_type = "Utiliser une wheel verticale ou arrondie",
    M_inf_wheel_speed = "Temps en milliseconds pour le défilement de la wheel",
    M_inf_wheel_fade = "Secondes pour atténué la wheel (0 ou - pour desactiver)",
    M_inf_wheel_fade_val = "Valeur alpha pour la wheel atténuée (0.0 - 1.0)",
    M_inf_wheel_slots = "Nombre de wheel à afficher",
    M_inf_wheel_stats = "Position des statistiques de la wheel",
    M_inf_wheel_pos = "Ajuster la position de la wheel",
    M_inf_gsurf_pos = "Position des infos jeu",
    M_inf_gametext_col = "Couleur du texte des infos jeu",
    M_inf_gametext_stroke = "Couleur bord de texte des infos jeu",
    M_inf_gametext = "Montre ou cache les infos jeu",
    M_inf_pointer_pos = "Position du pointeur de la wheel",
    M_inf_pointer_anim = "Utiliser un pointeur de wheel animé"
}

_LL["En"] <- {
    counter = "Play Count",
    playedtime = "Play Time",
    display = "Games / Filter",
    add_fav = "Added to favourites",
    ret_fav = "Removed from favourites",
    Sday = "D",
    Never = "Never",
    RefreshTxt = "Refreshing stats",
    Games = "Games",
    Played = "Played",
    Filter_all = "all",
    Yes = "Yes",
    No = "No",
    M_Menu_stretch = "Stretch",
    M_Menu_center = "Center",
    M_inf_Bezel = "Display or hide bezel on HS themes",
    M_inf_Bezel_top = "Put bezel on top of the theme artworks or below",
    M_inf_str_bckg =  "Stretch all backgrounds to current resolution",
    M_inf_flv =  "Enable or disable FLV Video Transitions",
    M_inf_theme = "Theme setting",
    M_inf_bck_trans = "Use background transitions",
    M_inf_reload_bck = "Reload transitions when navigating on default theme",
    M_inf_aspect = "Theme aspect (Stretch or Center real Hyperspin theme)",
    M_inf_syno = "Show/Hide scrolling synopsis",
    M_inf_game_sound = "Use ambiant games sound",
    M_inf_wheel_click = "Use wheel click sound",
    M_inf_wheel_type = "Switch between a vertical or rounded wheel",
    M_inf_wheel_speed = "Time in milliseconds for wheel spin",
    M_inf_wheel_fade = "Time in seconds for wheel fade out (negative value disable fading)",
    M_inf_wheel_fade_val = "Alpha value of the faded wheel (0.0 - 1.0)",
    M_inf_wheel_slots = "Number of wheel to display", 
    M_inf_wheel_stats = "position of the wheel stats infos",
    M_inf_wheel_pos = "Align the position of the wheel",
    M_inf_gsurf_pos = "position of the game info surface",
    M_inf_gametext_col = "Color of the game text font",
    M_inf_gametext_stroke = "Stroke color of the game text font",
    M_inf_gametext = "Enable or disable the Game Info Surface",
    M_inf_pointer_pos = "Wheel pointer position",
    M_inf_pointer_anim = "Use pointer animation"
    
    
}